from __future__ import annotations

import json
import os
import sys
from pathlib import Path

from dotenv import load_dotenv
from tqdm import tqdm

CURRENT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = CURRENT_DIR.parent
if str(PROJECT_DIR) not in sys.path:
    sys.path.insert(0, str(PROJECT_DIR))

from ingestion.embedder import generate_embedding, validate_embedding_dimension
from ingestion.graph_ingestor import GraphIngestor
from ingestion.neo4j_safety import require_local_ingestion

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    # Windows terminals default stdout to cp1252, which can't encode the
    # ✅ status marker printed below and crashes the run after ingestion
    # has already completed.
    sys.stdout.reconfigure(encoding="utf-8")

SUMMARIES_PATH = PROJECT_DIR / "data" / "summaries.json"
EXTRACTED_CLASSES_PATH = PROJECT_DIR / "data" / "extracted_classes.json"

# Max chars from document content used to generate embedding summary
DOCUMENT_EMBED_CHARS = 1_000


def _document_text(doc: dict) -> str:
    """Build a short text for embedding from a Document node."""
    parts = [f"File: {doc.get('relative_path', doc['fqn'])}"]
    content = (doc.get("content") or "")[:DOCUMENT_EMBED_CHARS]
    if content:
        parts.append(content)
    return "\n".join(parts)


def validate_summaries(summaries: object, extracted_classes: object) -> list[dict]:
    if not isinstance(summaries, list):
        raise ValueError("summaries.json must contain a JSON array")
    if not isinstance(extracted_classes, list):
        raise ValueError("extracted_classes.json must contain a JSON array")

    expected_fqns = {
        item.get("fqn")
        for item in extracted_classes
        if isinstance(item, dict) and isinstance(item.get("fqn"), str)
    }
    seen: set[str] = set()
    validated: list[dict] = []
    duplicates: set[str] = set()
    unknown: set[str] = set()

    for item in summaries:
        if not isinstance(item, dict):
            raise ValueError("Every summary entry must be a JSON object")
        fqn = item.get("fqn")
        summary = item.get("summary")
        if not isinstance(fqn, str) or not fqn:
            raise ValueError("Every summary entry must have a non-empty string fqn")
        if not isinstance(summary, str) or not summary.strip():
            raise ValueError(f"Summary must be non-empty for {fqn}")
        if fqn in seen:
            duplicates.add(fqn)
        if fqn not in expected_fqns:
            unknown.add(fqn)
        seen.add(fqn)
        validated.append({"fqn": fqn, "summary": summary})

    missing = expected_fqns - seen
    errors = []
    if duplicates:
        errors.append(f"duplicate FQNs: {', '.join(sorted(duplicates))}")
    if unknown:
        errors.append(f"unknown FQNs: {', '.join(sorted(unknown))}")
    if missing:
        errors.append(f"missing FQNs: {', '.join(sorted(missing))}")
    if errors:
        raise ValueError("; ".join(errors))
    return validated


def main() -> None:
    load_dotenv(PROJECT_DIR / ".env")

    neo4j_uri = os.getenv("NEO4J_URI", "bolt://localhost:7687")
    require_local_ingestion(neo4j_uri)

    ingestor = GraphIngestor(
        neo4j_uri,
        os.getenv("NEO4J_USER", "neo4j"),
        os.getenv("NEO4J_PASSWORD", "password123"),
    )

    model_name = os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")
    expected_dimension = int(os.getenv("EMBEDDING_DIM", "384"))

    try:
        # ── Embed :Class nodes (from summaries.json generated by LLM pipeline) ──
        summaries = validate_summaries(
            json.loads(SUMMARIES_PATH.read_text(encoding="utf-8")),
            json.loads(EXTRACTED_CLASSES_PATH.read_text(encoding="utf-8")),
        )
        for item in tqdm(summaries, desc="Embedding classes", unit="class"):
            embedding = generate_embedding(item["summary"], model_name=model_name)
            validate_embedding_dimension(embedding, expected_dimension, item["fqn"])
            ingestor.update_embedding(item["fqn"], embedding, item["summary"])

        # ── Embed :Document nodes (config files, markdown, yaml, etc.) ──────────
        with ingestor.driver.session() as session:
            result = session.run(
                "MATCH (d:Document) WHERE d.embedding IS NULL RETURN d.fqn AS fqn, d.content AS content, d.relative_path AS relative_path"
            )
            docs = [{"fqn": r["fqn"], "content": r["content"] or "", "relative_path": r["relative_path"] or r["fqn"]} for r in result]
        for doc in tqdm(docs, desc="Embedding documents", unit="doc"):
            text = _document_text(doc)
            embedding = generate_embedding(text, model_name=model_name)
            validate_embedding_dimension(embedding, expected_dimension, doc["fqn"])
            ingestor.update_document_embedding(doc["fqn"], embedding, text)

        print("✅ Fase 2 completa. Neo4j listo para consultas Graph RAG")
    finally:
        ingestor.close()


if __name__ == "__main__":
    main()
